async function loadErfa(moduleArg={}){var Module=moduleArg;var p=import.meta.url,r="",t;try{r=(new URL(".",p)).href}catch{}t=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var u=console.error.bind(console),v=!1;function x(){if(!y?.buffer?.resizable){var a=z.buffer;y=new Int8Array(a);A=new Int16Array(a);B=new Uint8Array(a);C=new Int32Array(a);D=new Uint32Array(a);E=new Float32Array(a);F=new Float64Array(a);G=new BigInt64Array(a)}}function I(){var a=Module.preRun;a&&(typeof a=="function"&&
(a=[a]),J.push(...a));for(a=J;a.length>0;)a.shift()(Module)}function K(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),L.push(...a));for(a=L;a.length>0;)a.shift()(Module)}function M(a){Module.onAbort?.(a);a=`Aborted(${a})`;u(a);v=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var N;async function P(a){try{var c=await t(a);return new Uint8Array(c)}catch{}throw"both async and sync fetching of the wasm failed";}async function Q(a,c){try{var d=await P(a);
return await WebAssembly.instantiate(d,c)}catch(b){u(`failed to asynchronously prepare wasm: ${b}`),M(b)}}async function R(a){var c=N;try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(b){u(`wasm streaming compile failed: ${b}`),u("falling back to ArrayBuffer instantiation")}return Q(c,a)}var y,L=[],J=[],B,S=new TextDecoder,W=(a,c,d,b)=>{var n={string:f=>{var h=0;if(f!==null&&f!==void 0&&f!==0){for(var e=h=0;e<f.length;++e){var g=f.charCodeAt(e);
g<=127?h++:g<=2047?h+=2:g>=55296&&g<=57343?(h+=4,++e):h+=3}var m=h+1;e=h=T(m);g=B;if(m>0){m=e+m-1;for(var w=0;w<f.length;++w){var k=f.codePointAt(w);if(k<=127){if(e>=m)break;g[e++]=k}else if(k<=2047){if(e+1>=m)break;g[e++]=192|k>>6;g[e++]=128|k&63}else if(k<=65535){if(e+2>=m)break;g[e++]=224|k>>12;g[e++]=128|k>>6&63;g[e++]=128|k&63}else{if(e+3>=m)break;g[e++]=240|k>>18;g[e++]=128|k>>12&63;g[e++]=128|k>>6&63;g[e++]=128|k&63;w++}}g[e]=0}}return h},array:f=>{var h=T(f.length);y.set(f,h);return h}};a=
Module["_"+a];var l=[],H=0;if(b)for(var q=0;q<b.length;q++){var O=n[d[q]];O?(H||=U(),l[q]=O(b[q])):l[q]=b[q]}d=a(...l);return d=function(f){H&&V(H);if(c==="string")if(f){for(var h=f,e=B,g=h+NaN;e[h]&&!(h>=g);)++h;f=S.decode(B.subarray(f,h))}else f="";else f=c==="boolean"?!!f:f;return f}(d)},A,C,D,E,F,G;Module.printErr&&(u=Module.printErr);var X=Module.preInit;if(X)for(typeof X=="function"&&(Module.preInit=X=[X]);X.length>0;)X.shift()();Module.ccall=W;Module.cwrap=(a,c,d,b)=>{var n=!d||d.every(l=>
l==="number"||l==="boolean");return c!=="string"&&n&&!b?Module["_"+a]:(...l)=>W(a,c,d,l,b)};Module.setValue=function(a,c,d="i8"){d.endsWith("*")&&(d="*");switch(d){case "i1":y[a]=c;break;case "i8":y[a]=c;break;case "i16":A[a>>1]=c;break;case "i32":C[a>>2]=c;break;case "i64":G[a>>3]=BigInt(c);break;case "float":E[a>>2]=c;break;case "double":F[a>>3]=c;break;case "*":D[a>>2]=c;break;default:M(`invalid type for setValue: ${d}`)}};Module.getValue=function(a,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":return y[a];
case "i8":return y[a];case "i16":return A[a>>1];case "i32":return C[a>>2];case "i64":return G[a>>3];case "float":return E[a>>2];case "double":return F[a>>3];case "*":return D[a>>2];default:M(`invalid type for getValue: ${c}`)}};var V,T,U,z,Y={a:a=>{var c=B.length;a>>>=0;if(a>2147483648)return!1;for(var d=1;d<=4;d*=2){var b=c*(1+.2/d);b=Math.min(b,a+100663296);a:{b=(Math.min(2147483648,Math.ceil(Math.max(a,b)/65536)*65536)-z.buffer.byteLength+65535)/65536|0;try{z.grow(b);x();var n=1;break a}catch(l){}n=
void 0}if(n)return!0}return!1}},Z;Z=await (async function(){function a(b){b=Z=b.exports;Module._eraDtf2d=b.d;Module._eraJd2cal=b.e;Module._eraAtoc13=b.f;Module._malloc=b.g;Module._free=b.h;V=b.i;T=b.j;U=b.k;z=b.b;x();return Z}var c={a:Y},d=Module.instantiateWasm;if(d)return new Promise(b=>{d(c,n=>b(a(n)))});N??=Module.locateFile?Module.locateFile?Module.locateFile("erfa.wasm",r):r+"erfa.wasm":(new URL("erfa.wasm",import.meta.url)).href;return function(b){return a(b.instance)}(await R(c))}());
await (async function(){I();var a=Module.setStatus;a&&(a("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(a,1,""));v||(Z.c(),Module.onRuntimeInitialized?.(),K())}());;return Module}export default loadErfa;
